-- Import Product-Ingredients.csv data into product_ingredients table
-- This script creates a temporary table, inserts CSV data, and then transfers to product_ingredients
-- Step 1: Create temporary table to hold CSV data
CREATE TEMP TABLE temp_product_ingredients (
    product_name TEXT,
    ingredient_name TEXT,
    quantity NUMERIC
);

-- Step 2: Insert CSV data into temporary table
INSERT INTO temp_product_ingredients (product_name, ingredient_name, quantity) VALUES
('Instant Sheera', 'Rava', 0.66),
('Instant Sheera', 'Vegetable Fat', 0.12),
('Instant Sheera', 'Common Salt', 0.005),
('Instant Sheera', 'Almonds', 0.0),
('Instant Sheera', 'Raisins', 0.0),
('Instant Sheera', 'Elaichi Essence', 0.001),
('Instant Sheera', 'Milk Powder', 0.0),
('Instant Sheera', 'Sugar', 0.6),
('Bhendi Masala', 'Peanuts', 0.7),
('Bhendi Masala', 'Sesame seeds', 0.0),
('Bhendi Masala', 'Turmeric', 0.01),
('Bhendi Masala', 'Edible Oil', 0.12),
('Bhendi Masala', 'Kanda Lasun', 0.08),
('Bhendi Masala', 'Common Salt', 0.05),
('Bhendi Masala', 'Jaggery', 0.09),
('Bhendi Masala', 'Aamchur', 0.04),
('Bhendi Masala', 'Cumin Seeds', 0.01),
('Bhendi Masala', 'Mustard Seeds', 0.01),
('Bhendi Masala', 'Goda Masala', 0.09),
('Bhendi Masala', 'VC', 0.0),
('Bhendi Masala', 'SB', 0.0),
('with mataki kolhapuri misal', 'Onion Tomato Gravy', 0.153),
('with mataki kolhapuri misal', 'Fried Onion Flakes', 0.071),
('with mataki kolhapuri misal', 'Dry Coconut', 0.071),
('with mataki kolhapuri misal', 'Chilli Ginger Garlic Paste', 0.122),
('with mataki kolhapuri misal', 'MIMASA Chicken Masala', 0.025),
('with mataki kolhapuri misal', 'Edible Oil', 0.204),
('with mataki kolhapuri misal', 'Sesame seeds', 0.015),
('with mataki kolhapuri misal', 'Gram Flour', 0.031),
('with mataki kolhapuri misal', 'CF', 0.031),
('with mataki kolhapuri misal', 'Kanda Lasun', 0.056),
('with mataki kolhapuri misal', 'Red Chilli Powder', 0.01),
('with mataki kolhapuri misal', 'Corriander Powder', 0.025),
('with mataki kolhapuri misal', 'White Salt', 0.002),
('with mataki kolhapuri misal', 'Garam Masala', 0.0),
('with mataki kolhapuri misal', 'Common Salt', 0.024),
('with mataki kolhapuri misal', 'Curry Leaves', 0.02),
('with mataki kolhapuri misal', 'lavangi plus kashmiri', 0.02),
('with mataki kolhapuri misal', 'Vit C', 0.001),
('with mataki kolhapuri misal', 'tamalpatra', 0.001),
('with mataki kolhapuri misal', 'SB', 0.002),
('with mataki kolhapuri misal', 'MATAKI DEHYDRATED', 0.2),
('kolhapuri misal', 'Onion Tomato Gravy', 0.573),
('kolhapuri misal', 'Fried Onion Flakes', 0.267),
('kolhapuri misal', 'Dry Coconut', 0.267),
('kolhapuri misal', 'Chilli Ginger Garlic Paste', 0.458),
('kolhapuri misal', 'MIMASA Chicken Masala', 0.095),
('kolhapuri misal', 'Edible Oil', 0.763),
('kolhapuri misal', 'Sesame seeds', 0.057),
('kolhapuri misal', 'Gram Flour', 0.115),
('kolhapuri misal', 'CF', 0.115),
('kolhapuri misal', 'Kanda Lasun', 0.21),
('kolhapuri misal', 'Red Chilli Powder', 0.038),
('kolhapuri misal', 'Corriander Powder', 0.095),
('kolhapuri misal', 'White Salt', 0.0),
('kolhapuri misal', 'Garam Masala', 0.0),
('kolhapuri misal', 'Common Salt', 0.09),
('kolhapuri misal', 'Curry Leaves', 0.076),
('kolhapuri misal', 'lavangi plus kashmiri', 0.076),
('kolhapuri misal', 'Vit C', 0.004),
('kolhapuri misal', 'tamalpatra', 0.004),
('kolhapuri misal', 'SB', 0.006),
('kolhapuri misal', 'Water', 0.0),
('Sambar Ready-Mix', 'Toor Dal + masur dal 1+ 2', 0.217),
('Sambar Ready-Mix', 'Chana Dal', 0.13),
('Sambar Ready-Mix', 'Rice', 0.087),
('Sambar Ready-Mix', 'Edible Oil', 0.042),
('Sambar Ready-Mix', 'Sambar Masala', 0.097),
('Sambar Ready-Mix', 'Red Chilli Powder', 0.013),
('Sambar Ready-Mix', 'Corriander Powder', 0.048),
('Sambar Ready-Mix', 'Turmeric Powder', 0.024),
('Sambar Ready-Mix', 'Tamarind Extract', 0.054),
('Sambar Ready-Mix', 'Common Salt', 0.109),
('Sambar Ready-Mix', 'Sugar', 0.109),
('Sambar Ready-Mix', 'Mustard Seeds', 0.007),
('Sambar Ready-Mix', 'Methi Seeds', 0.003),
('Sambar Ready-Mix', 'Hing', 0.001),
('Sambar Ready-Mix', 'Citric Acid', 0.001),
('Sambar Ready-Mix', 'Curry Leaves', 0.006),
('Sambar Ready-Mix', 'Tomato Powder', 0.085),
('Sambar Ready-Mix', 'Vit C', 0.0),
('Sambar Ready-Mix', 'SB', 0.0),
('AFGHANI Marinade', 'Water', 0.4),
('AFGHANI Marinade', 'Chilli Ginger Garlic Paste', 0.5),
('AFGHANI Marinade', 'Corriander Powder', 0.016),
('AFGHANI Marinade', 'Edible Oil', 0.008),
('AFGHANI Marinade', 'Cumin Powder', 0.006),
('AFGHANI Marinade', 'Common Salt', 0.02),
('AFGHANI Marinade', 'CF', 0.04),
('AFGHANI Marinade', 'Milk Powder', 0.007),
('AFGHANI Marinade', 'Vinegar 5%', 0.03),
('AFGHANI Marinade', 'Kasuri Methi', 0.002),
('AFGHANI Marinade', 'Black Pepper', 0.005),
('AFGHANI Marinade', 'X Gum', 0.002),
('AFGHANI Marinade', 'Green Chillies', 0.025),
('AFGHANI Marinade', 'White Salt', 0.002),
('AFGHANI Marinade', 'SB', 0.002),
('malai tikka marinade', 'Garlic Powder', 0.06),
('malai tikka marinade', 'ginger powder', 0.03),
('malai tikka marinade', 'Corriander Powder', 0.06),
('malai tikka marinade', 'cumin powder', 0.03),
('malai tikka marinade', 'Milk Powder', 0.06),
('malai tikka marinade', 'Cheese Powder', 0.02),
('malai tikka marinade', 'Common Salt', 0.18),
('malai tikka marinade', 'White Salt', 0.02),
('malai tikka marinade', 'Citric Acid', 0.01),
('malai tikka marinade', 'chat masala', 0.05),
('malai tikka marinade', 'Black Pepper Powder', 0.02),
('malai tikka marinade', 'CF', 0.43),
('malai tikka marinade', 'SiO2', 0.06),
('malai tikka marinade', 'SB', 0.0),
('Idli Mix', 'Idli Rava', 0.708),
('Idli Mix', 'Urad Dal', 0.195),
('Idli Mix', 'Pohe', 0.097),
('Idli Mix', 'Soda', 0.013),
('Idli Mix', 'Citric Acid', 0.012),
('Idli Mix', 'Common Salt', 0.017),
('MoongDal Bhaji', 'Moong Dal', 0.24),
('MoongDal Bhaji', 'Chana Dal', 0.24),
('MoongDal Bhaji', 'Gram Flour', 0.52),
('MoongDal Bhaji', 'Corriander Seeds', 0.004),
('MoongDal Bhaji', 'Cumin Seeds', 0.002),
('MoongDal Bhaji', 'Ajwain', 0.002),
('MoongDal Bhaji', 'Asafoetida', 0.002),
('MoongDal Bhaji', 'Turmeric', 0.003),
('MoongDal Bhaji', 'Common Salt', 0.026),
('MoongDal Bhaji', 'Soda', 0.004),
('MoongDal Bhaji', 'Citric Acid', 0.001),
('Instant Upma', 'Rava', 0.833),
('Instant Upma', 'Dehydrated Onion', 0.028),
('Instant Upma', 'Edible Oil', 0.08),
('Instant Upma', 'Common Salt', 0.04),
('Instant Upma', 'Green Chillies', 0.022),
('Instant Upma', 'Cumin Seeds', 0.006),
('Instant Upma', 'Ginger', 0.014),
('Instant Upma', 'Mustard Seeds', 0.006),
('Instant Upma', 'Urad Dal', 0.028),
('Instant Upma', 'Curry Leaves', 0.008),
('Instant Upma', 'Sugar', 0.067),
('Instant Upma', 'Citric Acid/Amchur', 0.001),
('Instant Upma', 'Asafoetida', 0.001),
('Instant Poha', 'Thick Pohe', 0.961),
('Instant Poha', 'Dehydrated Onion', 0.025),
('Instant Poha', 'Edible Oil', 0.075),
('Instant Poha', 'Common Salt', 0.03),
('Instant Poha', 'Green Chillies', 0.025),
('Instant Poha', 'Cumin Seeds', 0.003),
('Instant Poha', 'Turmeric Powder', 0.001),
('Instant Poha', 'Mustard Seeds', 0.003),
('Instant Poha', 'Peanuts', 0.05),
('Instant Poha', 'Curry Leaves', 0.008),
('Instant Poha', 'Sugar', 0.044),
('Instant Poha', 'Citric Acid/Amchur', 0.001),
('Instant Poha', 'Asafoetida', 0.001),
('rassa masala mix', 'ONION', 0.193),
('rassa masala mix', 'TOMATO POWDER', 0.043),
('rassa masala mix', 'Dry Coconut', 0.215),
('rassa masala mix', 'Curry Leaves', 0.013),
('rassa masala mix', 'Everest Chicken Masala', 0.107),
('rassa masala mix', 'Edible Oil', 0.107),
('rassa masala mix', 'Phutana Daal', 0.086),
('rassa masala mix', 'AKHHA LASUN', 0.043),
('rassa masala mix', 'GINGER', 0.017),
('rassa masala mix', 'Kanda Lasun', 0.043),
('rassa masala mix', 'Corriander Powder', 0.017),
('rassa masala mix', 'Cumin Powder', 0.009),
('rassa masala mix', 'Garam Masala', 0.021),
('rassa masala mix', 'Common Salt', 0.107),
('rassa masala mix', 'Red Chillies', 0.043),
('rassa masala mix', 'Vit C', 0.011),
('rassa masala mix', 'Color', 0.004),
('rassa masala mix', 'White Salt', 0.004),
('MUTTON spice mix', 'Fresh Corriander', 0.333),
('MUTTON spice mix', 'Cumin Seeds', 0.2),
('MUTTON spice mix', 'Dalchini', 0.067),
('MUTTON spice mix', 'Lavang', 0.053),
('MUTTON spice mix', 'tamalpatra', 0.053),
('MUTTON spice mix', 'Black Pepper', 0.067),
('MUTTON spice mix', 'star phul', 0.053),
('MUTTON spice mix', 'Mothi Velachi', 0.027),
('MUTTON spice mix', 'Choti Velachi', 0.04),
('MUTTON spice mix', 'badishep', 0.07),
('MUTTON spice mix', 'khas khas', 0.04),
('tikka powder', 'Besan', 0.1),
('tikka powder', 'SB', 0.001),
('tikka powder', 'Garlic Powder', 0.267),
('tikka powder', 'Ginger Powder', 0.067),
('tikka powder', 'Aamchur', 0.053),
('tikka powder', 'Red Chilli powder', 0.06),
('tikka powder', 'Ev. Tandoori Masala', 0.2),
('tikka powder', 'Tata Salt', 0.167),
('tikka powder', 'White Salt', 0.037),
('tikka powder', 'CF', 0.055),
('tikka powder', 'VC', 0.0),
('Imli Khajur Chutney', 'Water', 0.87),
('Imli Khajur Chutney', 'Jaggery', 0.248),
('Imli Khajur Chutney', 'Tamarind', 0.067),
('Imli Khajur Chutney', 'Dates', 0.067),
('Imli Khajur Chutney', 'Sea salt', 0.019),
('Imli Khajur Chutney', 'Black Salt', 0.005),
('Imli Khajur Chutney', 'Citric Acid', 0.0),
('Imli Khajur Chutney', 'Red chilli powder', 0.005),
('Imli Khajur Chutney', 'Cumin Powder', 0.005),
('Imli Khajur Chutney', 'Starch', 0.007),
('Imli Khajur Chutney', 'Xanthan Gum', 0.002),
('Imli Khajur Chutney', 'Color', 0.0),
('Imli Khajur Chutney', 'SB', 0.002),
('Batata Vada Ready-Mix', 'Dark Green Chillies', 0.35),
('Batata Vada Ready-Mix', 'Edible Oil', 0.167),
('Batata Vada Ready-Mix', 'Garlic peeled', 0.178),
('Batata Vada Ready-Mix', 'Turmeric Powder', 0.025),
('Batata Vada Ready-Mix', 'Common Salt', 0.024),
('Batata Vada Ready-Mix', 'Mustard Seeds', 0.022),
('Batata Vada Ready-Mix', 'Curry Leaves', 0.019),
('Batata Vada Ready-Mix', 'Ginger', 0.011),
('Batata Vada Ready-Mix', 'Hing', 0.002),
('Batata Vada Ready-Mix', 'Vit C', 0.001),
('Batata Vada Ready-Mix', 'SB', 0.002),
('Batata Vada Ready-Mix', 'Water', 0.259),
('Dabeli Ready-Mix', 'Edible Oil', 0.053),
('Dabeli Ready-Mix', 'Red Chilli Powder', 0.026),
('Dabeli Ready-Mix', 'Imli Khajur chutney', 0.35),
('Dabeli Ready-Mix', 'Dry Coconut', 0.158),
('Dabeli Ready-Mix', 'Dabeli Masala', 0.25),
('Dabeli Ready-Mix', 'Common Salt', 0.053),
('Dabeli Ready-Mix', 'SB', 0.002),
('Dabeli Ready-Mix', 'VC', 0.001),
('Dabeli Ready-Mix', 'Citric Acid', 0.002),
('Dabeli Ready-Mix', 'Water', 0.2),
('Hyderabadi Biryani Ready Gravy', 'Water', 0.0),
('Hyderabadi Biryani Ready Gravy', 'Onion Tomato Gravy', 0.645),
('Hyderabadi Biryani Ready Gravy', 'Chilli Ginger Garlic Paste', 0.065),
('Hyderabadi Biryani Ready Gravy', 'Fried Onions', 0.065),
('Hyderabadi Biryani Ready Gravy', 'Ev. Shahi Biryani Masala', 0.011),
('Hyderabadi Biryani Ready Gravy', 'MIMASA Chicken Masala', 0.017),
('Hyderabadi Biryani Ready Gravy', 'Gram Flour', 0.032),
('Hyderabadi Biryani Ready Gravy', 'CF', 0.022),
('Hyderabadi Biryani Ready Gravy', 'Edible Oil', 0.065),
('Hyderabadi Biryani Ready Gravy', 'Green Chillies', 0.008),
('Hyderabadi Biryani Ready Gravy', 'Fresh Corriander', 0.0),
('Hyderabadi Biryani Ready Gravy', 'Fresh Mint leaves', 0.0),
('Hyderabadi Biryani Ready Gravy', 'Red Chilli Powder', 0.01),
('Hyderabadi Biryani Ready Gravy', 'Corriander Powder', 0.008),
('Hyderabadi Biryani Ready Gravy', 'Cumin Powder', 0.005),
('Hyderabadi Biryani Ready Gravy', 'MIMASA BIRYANI MASALA', 0.011),
('Hyderabadi Biryani Ready Gravy', 'Whole Spices', 0.004),
('Hyderabadi Biryani Ready Gravy', 'Common Salt', 0.032),
('Hyderabadi Biryani Ready Gravy', 'White Salt', 0.006),
('Hyderabadi Biryani Ready Gravy', 'Vit C', 0.001),
('Hyderabadi Biryani Ready Gravy', 'SB', 0.003),
('Fish Fry Marinade', 'Chilli Ginger Garlic Paste', 0.5),
('Fish Fry Marinade', 'Malvani Masala', 0.04),
('Fish Fry Marinade', 'Red Chilli Powder', 0.012),
('Fish Fry Marinade', 'Turmeric Powder', 0.015),
('Fish Fry Marinade', 'CF', 0.03),
('Fish Fry Marinade', 'Gram Flour', 0.014),
('Fish Fry Marinade', 'Vinegar 5%', 0.06),
('Fish Fry Marinade', 'Common Salt', 0.075),
('Fish Fry Marinade', 'White Salt', 0.003),
('Fish Fry Marinade', 'Vit C', 0.001),
('Fish Fry Marinade', 'SB', 0.002),
('Fish Fry Marinade', 'Water', 0.292),
('Pahadi Kebab Marinade', 'Ginger Garlic Paste', 0.066),
('Pahadi Kebab Marinade', 'Edible Oil', 0.016),
('Pahadi Kebab Marinade', 'Chaat Masala', 0.035),
('Pahadi Kebab Marinade', 'Fresh Corriander', 0.181),
('Pahadi Kebab Marinade', 'Dark Green Chillieses', 0.062),
('Pahadi Kebab Marinade', 'Fresh Mint leaves', 0.026),
('Pahadi Kebab Marinade', 'Gram Flour', 0.022),
('Pahadi Kebab Marinade', 'CF', 0.022),
('Pahadi Kebab Marinade', 'Garam Masala', 0.004),
('Pahadi Kebab Marinade', 'Cumin Powder', 0.014),
('Pahadi Kebab Marinade', 'Common Salt', 0.018),
('Pahadi Kebab Marinade', 'Vinegar 5%', 0.003),
('Pahadi Kebab Marinade', 'Color', 0.004),
('Pahadi Kebab Marinade', 'White Salt', 0.002),
('Pahadi Kebab Marinade', 'Vit C', 0.001),
('Pahadi Kebab Marinade', 'SB', 0.002),
('Pahadi Kebab Marinade', 'Water', 0.714),
('Tandoori Marinade', 'Water', 0.468),
('Tandoori Marinade', 'Chilli Ginger Garlic Paste', 0.4),
('Tandoori Marinade', 'Red Chilli Powder', 0.029),
('Tandoori Marinade', 'Corriander Powder', 0.016),
('Tandoori Marinade', 'Edible Oil', 0.013),
('Tandoori Marinade', 'Cumin Powder', 0.006),
('Tandoori Marinade', 'Common Salt', 0.036),
('Tandoori Marinade', 'CF', 0.024),
('Tandoori Marinade', 'Tandoori Masala', 0.03),
('Tandoori Marinade', 'Vinegar 5%', 0.048),
('Tandoori Marinade', 'Kasuri Methi', 0.002),
('Tandoori Marinade', 'Color', 0.0),
('Tandoori Marinade', 'XGum', 0.002),
('Tandoori Marinade', 'Vit C', 0.001),
('Tandoori Marinade', 'White Salt', 0.004),
('Tandoori Marinade', 'SB', 0.002),
('Saoji Masala', 'Onion Tomato Gravy', 0.4),
('Saoji Masala', 'Fried Onions', 0.04),
('Saoji Masala', 'Chilli Ginger Garlic Paste', 0.05),
('Saoji Masala', 'Everest Meat Masala', 0.02),
('Saoji Masala', 'Jowar Flour', 0.008),
('Saoji Masala', 'Edible Oil', 0.02),
('Saoji Masala', 'Gram Flour', 0.015),
('Saoji Masala', 'Kala Masala', 0.013),
('Saoji Masala', 'Red Chilli Powder', 0.012),
('Saoji Masala', 'Corriander Powder', 0.01),
('Saoji Masala', 'Cumin Powder', 0.004),
('Saoji Masala', 'Garam Masala', 0.006),
('Saoji Masala', 'Kasuri Methi', 0.001),
('Saoji Masala', 'Common Salt', 0.03),
('Saoji Masala', 'Asafoetida', 0.002),
('Saoji Masala', 'White Salt', 0.002),
('Saoji Masala', 'Vit C', 0.001),
('Saoji Masala', 'SB', 0.002),
('Saoji Masala', 'Water', 0.4),
('Prawns Curry Ready Gravy', 'Water', 0.42),
('Prawns Curry Ready Gravy', 'Onion Tomato Gravy', 0.44),
('Prawns Curry Ready Gravy', 'Chilli Ginger Garlic Paste', 0.077),
('Prawns Curry Ready Gravy', 'Malvani Masala', 0.022),
('Prawns Curry Ready Gravy', 'Edible Oil', 0.02),
('Prawns Curry Ready Gravy', 'Red Chilli Powder', 0.0108),
('Prawns Curry Ready Gravy', 'Turmeric Powder', 0.005),
('Prawns Curry Ready Gravy', 'Corriander Powder', 0.01),
('Prawns Curry Ready Gravy', 'Soya Sauce', 0.005),
('Prawns Curry Ready Gravy', 'Vinegar 5%', 0.0),
('Prawns Curry Ready Gravy', 'Common Salt', 0.015),
('Prawns Curry Ready Gravy', 'Starch', 0.015),
('Prawns Curry Ready Gravy', 'XGum', 0.0),
('Prawns Curry Ready Gravy', 'Vit C', 0.001),
('Prawns Curry Ready Gravy', 'SB', 0.002),
('Mutton Rogan Josh Ready Gravy', 'Onion Tomato Gravy', 0.4),
('Mutton Rogan Josh Ready Gravy', 'Chilli Ginger Garlic Paste', 0.05),
('Mutton Rogan Josh Ready Gravy', 'Meat Masala', 0.02),
('Mutton Rogan Josh Ready Gravy', 'Gram Flour', 0.03),
('Mutton Rogan Josh Ready Gravy', 'CF', 0.03),
('Mutton Rogan Josh Ready Gravy', 'Edible Oil', 0.02),
('Mutton Rogan Josh Ready Gravy', 'Spice Mix', 0.004),
('Mutton Rogan Josh Ready Gravy', 'Corriander Powder', 0.012),
('Mutton Rogan Josh Ready Gravy', 'Cumin Powder', 0.007),
('Mutton Rogan Josh Ready Gravy', 'Red Chilli Powder', 0.018),
('Mutton Rogan Josh Ready Gravy', 'Common Salt', 0.03),
('Mutton Rogan Josh Ready Gravy', 'Garam Masala', 0.003),
('Mutton Rogan Josh Ready Gravy', 'White Salt', 0.001),
('Mutton Rogan Josh Ready Gravy', 'Vit C', 0.001),
('Mutton Rogan Josh Ready Gravy', 'SB', 0.002),
('Mutton Rogan Josh Ready Gravy', 'Water', 0.5),
('Veg Kadhai Ready Gravy', 'Water', 0.45),
('Veg Kadhai Ready Gravy', 'Onion Tomato Gravy', 0.4),
('Veg Kadhai Ready Gravy', 'Chilli Ginger Garlic Chutney', 0.04),
('Veg Kadhai Ready Gravy', 'Everest Chicken Masala', 0.024),
('Veg Kadhai Ready Gravy', 'Gram Flour', 0.016),
('Veg Kadhai Ready Gravy', 'CF', 0.008),
('Veg Kadhai Ready Gravy', 'Red Chilli Powder', 0.005),
('Veg Kadhai Ready Gravy', 'Corriander Powder', 0.012),
('Veg Kadhai Ready Gravy', 'Cumin Powder', 0.005),
('Veg Kadhai Ready Gravy', 'Edible Oil', 0.016),
('Veg Kadhai Ready Gravy', 'Garam Masala', 0.004),
('Veg Kadhai Ready Gravy', 'Common Salt', 0.024),
('Veg Kadhai Ready Gravy', 'Asafoetida', 0.001),
('Veg Kadhai Ready Gravy', 'X Gum', 0.0),
('Veg Kadhai Ready Gravy', 'Vit C', 0.0),
('Veg Kadhai Ready Gravy', 'SB', 0.002),
('Fish Curry Ready Gravy', 'Water', 0.437),
('Fish Curry Ready Gravy', 'Onion Tomato Gravy', 0.35),
('Fish Curry Ready Gravy', 'Chilli Ginger Garlic Paste', 0.07),
('Fish Curry Ready Gravy', 'Dessicated Coconut', 0.079),
('Fish Curry Ready Gravy', 'Malvani Masala', 0.038),
('Fish Curry Ready Gravy', 'Edible Oil', 0.017),
('Fish Curry Ready Gravy', 'Red Chilli Powder', 0.012),
('Fish Curry Ready Gravy', 'Turmeric Powder', 0.007),
('Fish Curry Ready Gravy', 'Corriander Powder', 0.009),
('Fish Curry Ready Gravy', 'Soya Sauce', 0.005),
('Fish Curry Ready Gravy', 'Vinegar 10%', 0.009),
('Fish Curry Ready Gravy', 'Common Salt', 0.019),
('Fish Curry Ready Gravy', 'Starch', 0.013),
('Fish Curry Ready Gravy', 'Vit C', 0.001),
('Fish Curry Ready Gravy', 'SB', 0.002),
('Mutton Curry Ready Gravy', 'Onion Tomato Gravy', 0.2),
('Mutton Curry Ready Gravy', 'Fried Onion Flakes', 0.08),
('Mutton Curry Ready Gravy', 'Dry Coconut', 0.08),
('Mutton Curry Ready Gravy', 'Chilli Ginger Garlic Paste', 0.08),
('Mutton Curry Ready Gravy', 'Everest Meat Masala', 0.04),
('Mutton Curry Ready Gravy', 'Edible Oil', 0.04),
('Mutton Curry Ready Gravy', 'Gram Flour', 0.012),
('Mutton Curry Ready Gravy', 'Starch', 0.012),
('Mutton Curry Ready Gravy', 'Kanda Lasun', 0.028),
('Mutton Curry Ready Gravy', 'Red Chilli Powder', 0.005),
('Mutton Curry Ready Gravy', 'Corriander Powder', 0.006),
('Mutton Curry Ready Gravy', 'Cumin Powder', 0.003),
('Mutton Curry Ready Gravy', 'Garam Masala', 0.005),
('Mutton Curry Ready Gravy', 'Spice Mix', 0.008),
('Mutton Curry Ready Gravy', 'Common Salt', 0.028),
('Mutton Curry Ready Gravy', 'White Salt', 0.003),
('Mutton Curry Ready Gravy', 'Vit C', 0.0),
('Mutton Curry Ready Gravy', 'SB', 0.002),
('Mutton Curry Ready Gravy', 'Water', 0.4),
('Egg-Chicken Curry Ready Gravy', 'Onion Tomato Gravy', 0.4),
('Egg-Chicken Curry Ready Gravy', 'Fried Onion Flakes', 0.04),
('Egg-Chicken Curry Ready Gravy', 'Dry Coconut', 0.04),
('Egg-Chicken Curry Ready Gravy', 'Chilli Ginger Garlic Paste', 0.05),
('Egg-Chicken Curry Ready Gravy', 'Everest Chicken Masala', 0.04),
('Egg-Chicken Curry Ready Gravy', 'Edible Oil', 0.04),
('Egg-Chicken Curry Ready Gravy', 'Gram Flour', 0.012),
('Egg-Chicken Curry Ready Gravy', 'Starch', 0.012),
('Egg-Chicken Curry Ready Gravy', 'Kanda Lasun', 0.028),
('Egg-Chicken Curry Ready Gravy', 'Red Chilli Powder', 0.005),
('Egg-Chicken Curry Ready Gravy', 'Corriander Powder', 0.006),
('Egg-Chicken Curry Ready Gravy', 'Cumin Powder', 0.003),
('Egg-Chicken Curry Ready Gravy', 'Garam Masala', 0.005),
('Egg-Chicken Curry Ready Gravy', 'Common Salt', 0.024),
('Egg-Chicken Curry Ready Gravy', 'White Salt', 0.003),
('Egg-Chicken Curry Ready Gravy', 'Vit C', 0.001),
('Egg-Chicken Curry Ready Gravy', 'SB', 0.0),
('Egg-Chicken Curry Ready Gravy', 'Water', 0.325),
('Shev Bhaji', 'Onion Tomato Gravy', 0.428),
('Shev Bhaji', 'Fried Onion Flakes', 0.026),
('Shev Bhaji', 'Dry Coconut', 0.026),
('Shev Bhaji', 'Chilli Ginger Garlic Paste', 0.086),
('Shev Bhaji', 'Misal Masala', 0.0),
('Shev Bhaji', 'Edible Oil', 0.051),
('Shev Bhaji', 'Sesame seeds', 0.012),
('Shev Bhaji', 'Gram Flour', 0.021),
('Shev Bhaji', 'CF', 0.021),
('Shev Bhaji', 'Kanda Lasun', 0.045),
('Shev Bhaji', 'Red Chilli Powder', 0.007),
('Shev Bhaji', 'Corriander Powder', 0.009),
('Shev Bhaji', 'Cumin Powder', 0.003),
('Shev Bhaji', 'Garam Masala', 0.005),
('Shev Bhaji', 'Common Salt', 0.019),
('Shev Bhaji', 'White Salt', 0.003),
('Shev Bhaji', 'Citric Acid', 0.0),
('Shev Bhaji', 'Vit C', 0.001),
('Shev Bhaji', 'X Gum', 0.0),
('Shev Bhaji', 'SB', 0.002),
('Shev Bhaji', 'Water', 0.282),
('Chole-Rajma Masala Ready Gravy', 'Onion Tomato Gravy', 0.42),
('Chole-Rajma Masala Ready Gravy', 'Chilli Ginger Garlic Paste', 0.05),
('Chole-Rajma Masala Ready Gravy', 'Everest Chole Masala', 0.03),
('Chole-Rajma Masala Ready Gravy', 'Edible Oil', 0.01),
('Chole-Rajma Masala Ready Gravy', 'Gram Flour', 0.02),
('Chole-Rajma Masala Ready Gravy', 'Starch', 0.012),
('Chole-Rajma Masala Ready Gravy', 'Red Chilli Powder', 0.007),
('Chole-Rajma Masala Ready Gravy', 'Corriander Powder', 0.015),
('Chole-Rajma Masala Ready Gravy', 'Kasuri Methi', 0.002),
('Chole-Rajma Masala Ready Gravy', 'Garam Masala', 0.004),
('Chole-Rajma Masala Ready Gravy', 'Common Salt', 0.018),
('Chole-Rajma Masala Ready Gravy', 'Vit C', 0.001),
('Chole-Rajma Masala Ready Gravy', 'SB', 0.002),
('Chole-Rajma Masala Ready Gravy', 'Water', 0.421),
('Chicken Curry Dhaba Style Gravy', 'Water', 0.32),
('Chicken Curry Dhaba Style Gravy', 'Onion Tomato Gravy', 0.5),
('Chicken Curry Dhaba Style Gravy', 'Chilli Ginger Garlic Paste', 0.06),
('Chicken Curry Dhaba Style Gravy', 'Ev. Chicken Masala', 0.021),
('Chicken Curry Dhaba Style Gravy', 'Gram Flour', 0.024),
('Chicken Curry Dhaba Style Gravy', 'Edible Oil', 0.012),
('Chicken Curry Dhaba Style Gravy', 'Red Chilli Powder', 0.018),
('Chicken Curry Dhaba Style Gravy', 'Corriander Powder', 0.01),
('Chicken Curry Dhaba Style Gravy', 'Cumin Powder', 0.005),
('Chicken Curry Dhaba Style Gravy', 'Garam Masala', 0.005),
('Chicken Curry Dhaba Style Gravy', 'Common Salt', 0.019),
('Chicken Curry Dhaba Style Gravy', 'Starch', 0.016),
('Chicken Curry Dhaba Style Gravy', 'White Salt', 0.002),
('Chicken Curry Dhaba Style Gravy', 'Vit C', 0.0),
('Chicken Curry Dhaba Style Gravy', 'SB', 0.002),
('Paneer Butter Masala Ready Gravy', 'Onion Tomato Gravy', 0.25),
('Paneer Butter Masala Ready Gravy', 'Chilli Ginger Garlic Paste', 0.038),
('Paneer Butter Masala Ready Gravy', 'Makhni gravy', 0.333),
('Paneer Butter Masala Ready Gravy', 'Edible Oil', 0.013),
('Paneer Butter Masala Ready Gravy', 'Gram Flour', 0.025),
('Paneer Butter Masala Ready Gravy', 'Starch', 0.013),
('Paneer Butter Masala Ready Gravy', 'Everest Chicken Masala', 0.019),
('Paneer Butter Masala Ready Gravy', 'Corriander Powder', 0.008),
('Paneer Butter Masala Ready Gravy', 'Cumin Powder', 0.003),
('Paneer Butter Masala Ready Gravy', 'Red Chilli Powder', 0.003),
('Paneer Butter Masala Ready Gravy', 'Garam Masala', 0.003),
('Paneer Butter Masala Ready Gravy', 'Common Salt', 0.023),
('Paneer Butter Masala Ready Gravy', 'Sugar', 0.031),
('Paneer Butter Masala Ready Gravy', 'Kasuri Methi', 0.001),
('Paneer Butter Masala Ready Gravy', 'Vit C', 0.0),
('Paneer Butter Masala Ready Gravy', 'White Salt', 0.003),
('Paneer Butter Masala Ready Gravy', 'Sodium Benzoate', 0.001),
('Paneer Butter Masala Ready Gravy', 'XGum', 0.0),
('Paneer Butter Masala Ready Gravy', 'Water', 0.275);

-- Step 3: Clear existing product_ingredients data (optional - uncomment if you want to replace all data)
 DELETE FROM product_ingredients;

-- Step 4: Insert data from temporary table into product_ingredients table
INSERT INTO product_ingredients (product_id, ingredient_id, quantity)
SELECT 
    (SELECT p.id FROM products p WHERE p.name = t.product_name AND p.active = true LIMIT 1) as product_id,
    (SELECT i.id FROM ingredients i WHERE LOWER(i.name) LIKE '%' || LOWER(t.ingredient_name) || '%' AND i.active = true LIMIT 1) as ingredient_id,
    t.quantity
FROM temp_product_ingredients t
WHERE t.quantity > 0
  AND EXISTS (SELECT 1 FROM products p WHERE p.name = t.product_name AND p.active = true)
  AND EXISTS (SELECT 1 FROM ingredients i WHERE LOWER(i.name) LIKE '%' || LOWER(t.ingredient_name) || '%' AND i.active = true);

-- Step 5: Show summary of imported data
SELECT 
    COUNT(*) as total_records_imported,
    COUNT(DISTINCT product_id) as unique_products,
    COUNT(DISTINCT ingredient_id) as unique_ingredients
FROM product_ingredients 
WHERE created_at >= NOW() - INTERVAL '1 minute'; -- Records created in the last minute

-- Step 6: Show any products or ingredients that couldn't be matched
SELECT 
    'Unmatched Products' as issue_type,
    t.product_name as name,
    COUNT(*) as count
FROM temp_product_ingredients t
LEFT JOIN products p ON p.name = t.product_name AND p.active = true
WHERE p.id IS NULL
GROUP BY t.product_name

UNION ALL

SELECT 
    'Unmatched Ingredients' as issue_type,
    t.ingredient_name as name,
    COUNT(*) as count
FROM temp_product_ingredients t
LEFT JOIN ingredients i ON i.name = t.ingredient_name AND i.active = true
WHERE i.id IS NULL
GROUP BY t.ingredient_name

ORDER BY issue_type, count DESC;

-- Step 7: Clean up temporary table
DROP TABLE temp_product_ingredients;
