// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smbfkkufffdgbruatsts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtYmZra3VmZmZkZ2JydWF0c3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTQyNTYsImV4cCI6MjA2NDM3MDI1Nn0.wiDwA5FAs2oeGaF4p2SA6Ns3CqutvJx5ME2Tibu8sAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);